#!/usr/bin/env python3
"""Build a deterministic empty-schema SQL bootstrap from canonical components."""
from pathlib import Path
import argparse
import json
import sys

ROOT = Path(__file__).resolve().parents[1]
HEADER = """-- Generated by scripts/build_sql.py. Edit components, then rebuild.
-- Fresh PostgreSQL 17+ database / empty public schema only. No personal rows.
-- Apply as database owner using psql -X -v ON_ERROR_STOP=1 -f database/bootstrap.sql.
BEGIN;
SET LOCAL search_path = public, pg_catalog;
DO $preflight$
BEGIN
  IF current_setting('server_version_num')::integer < 170000 THEN
    RAISE EXCEPTION 'cashflow-gpt requires PostgreSQL 17 or newer';
  END IF;
  IF EXISTS (
    SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
    WHERE n.nspname='public' AND c.relkind IN ('r','p','v','m','S','f')
  ) OR EXISTS (
    SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace
    WHERE n.nspname='public'
  ) THEN
    RAISE EXCEPTION 'cashflow-gpt bootstrap requires an empty public schema; use a new database';
  END IF;
END $preflight$;
CREATE SCHEMA IF NOT EXISTS public;
-- Functions and views refer to each other; bodies are checked again by tests after installation.
SET LOCAL check_function_bodies = false;
"""
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    manifest = json.loads((ROOT/"database/manifest.json").read_text())
    components = manifest["components"]
    if len(components) != len(set(components)):
        raise ValueError("Duplicate SQL components")
    parts = [HEADER]
    for rel in components:
        p = (ROOT/rel).resolve()
        if ROOT not in p.parents or p.suffix != ".sql":
            raise ValueError("Invalid component path: "+rel)
        parts.append("\n-- Component: "+rel+"\n"+p.read_text().rstrip()+"\n")
    result = "".join(parts)+"\nSET LOCAL check_function_bodies = true;\nCOMMIT;\n"
    target = ROOT/"database/bootstrap.sql"
    if args.check:
        if not target.exists() or target.read_text() != result:
            print("Bootstrap is stale; run python3 scripts/build_sql.py",file=sys.stderr)
            return 1
        print("OK: bootstrap matches "+str(len(components))+" components")
    else:
        target.write_text(result)
        print("Built database/bootstrap.sql from "+str(len(components))+" components")
    return 0

if __name__ == "__main__":
    sys.exit(main())

