CREATE TABLE public."accounts" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public."accounts_id_seq" START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 NO CYCLE) NOT NULL,
  "name" text NOT NULL,
  "account_type" text NOT NULL,
  "currency" text DEFAULT 'RUB'::text NOT NULL,
  "institution" text,
  "credit_limit" numeric(14,2),
  "opening_balance" numeric(14,2) DEFAULT 0 NOT NULL,
  "opening_balance_date" date,
  "is_active" boolean DEFAULT true NOT NULL,
  "notes" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
