CREATE TABLE public."cash_flow_events" (
  "id" bigint DEFAULT nextval('cash_flow_events_id_seq'::regclass) NOT NULL,
  "event_date" date NOT NULL,
  "event_type" text NOT NULL,
  "amount" numeric NOT NULL,
  "description" text NOT NULL,
  "account_id" bigint,
  "liability_id" bigint,
  "is_planned" boolean DEFAULT true NOT NULL,
  "is_secured" boolean DEFAULT false NOT NULL,
  "source_transaction_id" bigint,
  "notes" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "rule_id" bigint,
  "period_start" date,
  "period_end" date,
  "calculation_method" text,
  "living_budget_exempt" boolean DEFAULT false NOT NULL,
  "security_amount" numeric,
  "status" text DEFAULT 'planned'::text NOT NULL,
  "actual_amount" numeric,
  "actual_date" date,
  "source_type" text DEFAULT 'manual'::text NOT NULL,
  "source_key" text,
  "fulfillment_mode" text DEFAULT 'dated_payment'::text NOT NULL,
  "liability_payment_schedule_id" bigint,
  "income_completed_at" timestamp with time zone
);
