CREATE TABLE public."categories" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public."categories_id_seq" START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 NO CYCLE) NOT NULL,
  "name" text NOT NULL,
  "category_type" text NOT NULL,
  "parent_id" bigint,
  "is_active" boolean DEFAULT true NOT NULL
);
