CREATE TABLE public."debt_payment_details" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public."debt_payment_details_id_seq" START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 NO CYCLE) NOT NULL,
  "transaction_id" bigint NOT NULL,
  "liability_id" bigint NOT NULL,
  "principal_amount" numeric(14,2) DEFAULT 0 NOT NULL,
  "interest_amount" numeric(14,2) DEFAULT 0 NOT NULL,
  "fee_amount" numeric(14,2) DEFAULT 0 NOT NULL,
  "cash_flow_event_id" bigint
);
