CREATE TABLE public."debt_goals" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public."debt_goals_id_seq" START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 NO CYCLE) NOT NULL,
  "liability_id" bigint NOT NULL,
  "target_close_date" date,
  "target_monthly_payment" numeric(14,2),
  "target_extra_payment" numeric(14,2),
  "priority" smallint,
  "rationale" text,
  "is_active" boolean DEFAULT true NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
