CREATE TABLE public."liability_movements" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public."liability_movements_id_seq" START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 NO CYCLE) NOT NULL,
  "liability_id" bigint NOT NULL,
  "effective_at" timestamp with time zone NOT NULL,
  "movement_type" text NOT NULL,
  "amount" numeric NOT NULL,
  "direction" smallint DEFAULT 1 NOT NULL,
  "transaction_id" bigint,
  "cash_flow_event_id" bigint,
  "notes" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "debt_payment_detail_id" bigint
);
