CREATE TABLE public."liability_balance_snapshots" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public."liability_balance_snapshots_id_seq" START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 NO CYCLE) NOT NULL,
  "liability_id" bigint NOT NULL,
  "balance_as_of" timestamp with time zone NOT NULL,
  "principal_balance" numeric NOT NULL,
  "accrued_interest" numeric DEFAULT 0 NOT NULL,
  "fees_due" numeric DEFAULT 0 NOT NULL,
  "source" text,
  "notes" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
