CREATE TABLE public."liability_payment_schedule" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public."liability_payment_schedule_id_seq" START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 NO CYCLE) NOT NULL,
  "liability_id" bigint NOT NULL,
  "payment_number" integer,
  "payment_date" date NOT NULL,
  "principal_before" numeric NOT NULL,
  "principal_amount" numeric NOT NULL,
  "interest_amount" numeric DEFAULT 0 NOT NULL,
  "fee_amount" numeric DEFAULT 0 NOT NULL,
  "total_amount" numeric NOT NULL,
  "principal_after" numeric GENERATED ALWAYS AS (GREATEST((principal_before - principal_amount), (0)::numeric)) STORED,
  "source" text,
  "source_as_of" date,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
