CREATE TABLE public."living_budgets" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public."living_budgets_id_seq" START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 NO CYCLE) NOT NULL,
  "week_start" date NOT NULL,
  "amount" numeric NOT NULL,
  "notes" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
