CREATE TABLE public."planned_purchases" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public."planned_purchases_id_seq" START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 NO CYCLE) NOT NULL,
  "name" text NOT NULL,
  "planned_amount" numeric NOT NULL,
  "planned_date" date,
  "status" text DEFAULT 'active'::text NOT NULL,
  "financing_method" text,
  "actual_transaction_id" bigint,
  "liability_id" bigint,
  "notes" text,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "closed_at" timestamp with time zone
);
